version: "3.9"

services:

  test-ui:
    build:
      context: ..
      dockerfile: ./docker/server/node.Dockerfile
    environment:
      - REACT_APP_PROJECT_NAME="TEST APP"
      - REACT_APP_PROJECT_DESCRIPTION="It's test text only"
    volumes:
      - ../public/results:/code/results # It's important,
    ports:
      - "8087:3002"