version: "3.9"

services:

  test-ui:
#    build:
#      context: ..
#      dockerfile: server/Dockerfile
    image: igor368/venom-cli-requests-ui:v0.0.2
    environment:
      - REACT_APP_PROJECT_NAME="TEST APP111"
      - REACT_APP_PROJECT_DESCRIPTION="It's test text only"
    volumes:
      - ../public/results:/code/results # It's important,
    ports:
      - "8087:3002"